name: 'Increment Version - npm'
on:
  pull_request:
    branches:
      - main
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  version:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-check-increment-npm.yml@v1
    with:
      mainLineBranchName: main
