name: 'Test'
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/test-npm.yml@v1
    secrets: inherit
    with:
      lintCommand: 'test:lint'
      testCommand: 'run test:unit'

